### ISSUE TITLE
Add code checking for notebooks

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cell-census#116]
Currently we don't do any linting or type check of the notebooks. The rest of the code base is check using black, flake8, isort, and mypy. https://github.com/nbQA-dev/nbQA is a library for running these tools on notebooks. This one encompasses all the tools bellow plus additional tools such as ruff. It also support pre-commit which we are starting to use more.

Other libraries to concider:
- https://pypi.org/project/nb-mypy/
- black[jupyter]

### Pre-commit
If we decide to use pre-commit
```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
        files: ^api/python/notebooks
        args: ["--config", "./api/python/notebooks/pyproject.toml"]
      - id: nbqa-ruff
        args: [ "--config=./api/python/notebooks/pyproject.toml", "--fix" ]
        files: ^api/python/notebooks
      - id: nbqa-mypy
        files: ^api/python/notebooks
        args: ["--config-file=./api/python/notebooks/pyproject.toml"]
        additional_dependencies:
          - mypy==0.982
          - numpy
```
